"""
spatial_reduce_report.py — OmicSage Phase 7, Session 5 (style update)
HTML report for spatial reduction results.

Style: matches spatial_qc_report.py exactly (_PAGE_CSS / _render_page pattern).

Sections:
  1. Run Summary       — stat cards: spots, genes, HVGs, PCA components, variance
  2. HVG selection     — mean vs dispersion scatter (HVGs highlighted)
  3. PCA               — elbow plot + PCA scatter coloured by total_counts
  4. Spatial structure — spatial scatter of top HVG on tissue + neighbours histogram
                         (mirrors tutorial: sq.pl.spatial_scatter with img_key)
"""

from __future__ import annotations

import base64
import logging
import os
from datetime import datetime
from io import BytesIO
from pathlib import Path
from typing import Optional

import anndata as ad
import matplotlib
import matplotlib.pyplot as plt
import numpy as np

matplotlib.use("Agg")
logger = logging.getLogger(__name__)

try:
    import squidpy as sq
    _SQUIDPY_AVAILABLE = True
except ImportError:
    _SQUIDPY_AVAILABLE = False


# ---------------------------------------------------------------------------
# Shared CSS + page renderer  (identical to spatial_qc_report.py)
# ---------------------------------------------------------------------------

_PAGE_CSS = """
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
           font-size: 14px; line-height: 1.6; color: #1a1a2e; background: #f7f8fc; }
    header { background: linear-gradient(135deg, #1a1a2e 0%, #16213e 60%, #0f3460 100%);
             color: white; padding: 32px 40px 24px; }
    header h1 { font-size: 1.8rem; font-weight: 700; letter-spacing: -0.5px; }
    header p  { font-size: 0.85rem; opacity: 0.7; margin-top: 4px; }
    main { max-width: 1100px; margin: 0 auto; padding: 32px 24px; }
    section { background: white; border-radius: 10px;
              box-shadow: 0 1px 4px rgba(0,0,0,0.07);
              padding: 28px 32px; margin-bottom: 24px; }
    section h2 { font-size: 1.15rem; font-weight: 700; color: #0f3460;
                 border-bottom: 2px solid #e8eaf6; padding-bottom: 10px; margin-bottom: 18px; }
    section h3 { font-size: 1rem; font-weight: 600; color: #16213e; margin: 18px 0 10px; }
    section p  { color: #444; margin-bottom: 12px; font-size: 0.9rem; }
    .timestamp { font-size: 0.8rem; color: #888; margin-bottom: 6px; }
    .note { font-size: 0.82rem; color: #7a5c00; background: #fffbe6;
            border-left: 3px solid #f0c040; padding: 8px 12px;
            border-radius: 4px; margin-bottom: 14px; }
    code { font-family: "SFMono-Regular", Consolas, monospace;
           background: #f0f2ff; padding: 1px 5px; border-radius: 3px; font-size: 0.85em; }
    .stat-grid { display: flex; flex-wrap: wrap; gap: 14px; margin-bottom: 24px; }
    .stat-card { background: #f0f2ff; border-radius: 8px; padding: 14px 20px;
                 min-width: 130px; text-align: center; flex: 1 1 130px; }
    .stat-value { font-size: 1.4rem; font-weight: 700; color: #0f3460; }
    .stat-label { font-size: 0.75rem; color: #666; margin-top: 2px; }
    table { width: 100%; border-collapse: collapse; font-size: 0.88rem; margin-top: 8px; }
    th { background: #f0f2ff; color: #0f3460; font-weight: 600;
         padding: 9px 12px; text-align: left; border-bottom: 2px solid #d0d4f0; }
    td { padding: 8px 12px; border-bottom: 1px solid #eee; vertical-align: middle; }
    tr:last-child td { border-bottom: none; }
    tr:hover td { background: #f8f9ff; }
    .fig-grid { display: flex; flex-wrap: wrap; gap: 18px; margin-top: 12px; }
    .fig-wrap { flex: 1 1 420px; max-width: 100%; }
    .fig-wrap h3 { font-size: 0.9rem; margin-bottom: 6px; color: #16213e; }
    .fig-wrap img { width: 100%; border-radius: 6px; border: 1px solid #e8eaf6; cursor: zoom-in; display: block; }
    footer { text-align: center; font-size: 0.78rem; color: #aaa; padding: 24px 0 32px; }
    footer a { color: #0f3460; text-decoration: none; }
"""


def _render_page(title: str, header_subtitle: str, sections: list[str], timestamp: str) -> str:
    body = "\n".join(sections)
    return (
        "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n"
        "  <meta charset=\"UTF-8\">\n"
        "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
        f"  <title>{title}</title>\n"
        f"  <style>{_PAGE_CSS}</style>\n"
        "</head>\n<body>\n"
        "  <header>\n"
        "    <h1>OmicSage &#8212; Spatial Reduce Report</h1>\n"
        f"    <p>{header_subtitle} &middot; Generated {timestamp}</p>\n"
        "  </header>\n"
        "  <main>\n"
        f"    {body}\n"
        "  </main>\n"
        "  <footer>\n"
        "    Generated by <a href=\"https://github.com/fshokor/OmicSage\">OmicSage</a>\n"
        "    &middot; MIT License\n"
        "  </footer>\n"
        "</body>\n</html>"
    )


# ---------------------------------------------------------------------------
# Figure helpers
# ---------------------------------------------------------------------------


def _squidpy_panel_figsize(adata, per_panel=(6, 6), max_total_w=18):
    """Return per-panel figsize unchanged; multi-sample handled in _squidpy_scatter_b64."""
    return per_panel

def _fig_to_b64(fig: plt.Figure) -> str:
    buf = BytesIO()
    fig.savefig(buf, format="png", dpi=100, bbox_inches="tight")
    buf.seek(0)
    b64 = base64.b64encode(buf.read()).decode()
    plt.close(fig)
    return b64

def _squidpy_scatter_b64(
    adata,
    color,
    img_key=None,
    library_key=None,
    title=None,
    figsize=(6, 6),
):
    """Render sq.pl.spatial_scatter and return a base64 PNG.

    Multi-sample strategy: render each sample separately and stitch into a
    2-column grid.  squidpy's side-by-side layout produces extreme aspect
    ratios (~9:1) with 4 samples, which are unreadable at browser column widths.
    """
    import numpy as _np
    import io as _io
    import base64 as _b64_mod

    if not _SQUIDPY_AVAILABLE:
        return None

    try:
        samples = []
        if library_key and library_key in adata.obs.columns:
            samples = sorted(adata.obs[library_key].astype(str).unique().tolist())

        # ── Single-sample fast path ──────────────────────────────────────────
        if len(samples) <= 1:
            plt.close("all")
            kwargs = dict(color=color, frameon=False, figsize=figsize)
            if img_key:
                kwargs["img_res_key"] = img_key
            result = sq.pl.spatial_scatter(adata, **kwargs)
            if result is None:
                fig = plt.gcf()
            elif hasattr(result, "get_figure"):
                fig = result.get_figure()
            elif hasattr(result, "__len__") and len(result) > 0:
                ax0 = result[0]
                fig = ax0.get_figure() if hasattr(ax0, "get_figure") else plt.gcf()
            else:
                fig = plt.gcf()
            if not fig.axes:
                all_figs = [plt.figure(n) for n in plt.get_fignums()]
                if all_figs:
                    fig = all_figs[-1]
            if title:
                fig.suptitle(title, fontsize=10, fontweight="bold")
            try:
                fig.tight_layout()
            except Exception:
                pass
            return _fig_to_b64(fig)

        # ── Multi-sample: per-sample render + 2-column grid stitch ───────────
        per_b64s: list = []
        for sample_id in samples:
            try:
                mask = adata.obs[library_key].astype(str) == sample_id
                ad_sub = adata[mask].copy()
                # uns["spatial"] is not filtered by obs subsetting — prune to
                # the current sample so squidpy doesn't demand a library_key.
                if "spatial" in ad_sub.uns and sample_id in ad_sub.uns["spatial"]:
                    ad_sub.uns["spatial"] = {sample_id: ad_sub.uns["spatial"][sample_id]}
                plt.close("all")
                kwargs = dict(color=color, frameon=False, figsize=figsize)
                if img_key:
                    kwargs["img_res_key"] = img_key
                result = sq.pl.spatial_scatter(ad_sub, **kwargs)
                if result is None:
                    fig = plt.gcf()
                elif hasattr(result, "get_figure"):
                    fig = result.get_figure()
                elif hasattr(result, "__len__") and len(result) > 0:
                    ax0 = result[0]
                    fig = ax0.get_figure() if hasattr(ax0, "get_figure") else plt.gcf()
                else:
                    fig = plt.gcf()
                if not fig.axes:
                    all_figs = [plt.figure(n) for n in plt.get_fignums()]
                    if all_figs:
                        fig = all_figs[-1]
                try:
                    fig.tight_layout()
                except Exception:
                    pass
                buf = _io.BytesIO()
                fig.savefig(buf, format="png", dpi=100, bbox_inches="tight")
                buf.seek(0)
                per_b64s.append((sample_id, _b64_mod.b64encode(buf.read()).decode()))
                plt.close(fig)
            except Exception as e:
                logger.warning("[reduce_report] scatter failed for sample %s: %s", sample_id, e)
                plt.close("all")

        if not per_b64s:
            return None

        imgs = [plt.imread(_io.BytesIO(_b64_mod.b64decode(b))) for _, b in per_b64s]
        ncols = 2
        nrows = (len(imgs) + ncols - 1) // ncols
        max_h = max(a.shape[0] for a in imgs)
        max_w = max(a.shape[1] for a in imgs)
        n_ch  = imgs[0].shape[2] if imgs[0].ndim == 3 else 1

        def _pad(a):
            return _np.pad(a,
                           ((0, max_h - a.shape[0]), (0, max_w - a.shape[1]), (0, 0)),
                           mode="constant", constant_values=1.0)

        padded = [_pad(a) for a in imgs]
        while len(padded) < nrows * ncols:
            padded.append(_np.ones((max_h, max_w, n_ch), dtype=padded[0].dtype))

        grid = _np.vstack([_np.hstack(padded[r * ncols:(r + 1) * ncols])
                           for r in range(nrows)])

        dpi = 100
        title_pad = 0.35 if title else 0.0
        fig2, ax2 = plt.subplots(
            figsize=(grid.shape[1] / dpi, grid.shape[0] / dpi + title_pad), dpi=dpi)
        ax2.imshow(grid)
        ax2.axis("off")
        if title:
            fig2.suptitle(title, fontsize=10, fontweight="bold")
        for idx, (sample_id, _) in enumerate(per_b64s):
            row_i, col_i = idx // ncols, idx % ncols
            ax2.text(col_i * max_w + max_w * 0.02, row_i * max_h + max_h * 0.04,
                     sample_id, fontsize=8, fontweight="bold", color="white", va="top",
                     bbox=dict(facecolor="black", alpha=0.45, pad=2, linewidth=0))
        fig2.subplots_adjust(left=0, right=1, top=1, bottom=0)
        buf2 = _io.BytesIO()
        fig2.savefig(buf2, format="png", dpi=dpi, bbox_inches="tight")
        buf2.seek(0)
        result_b64 = _b64_mod.b64encode(buf2.read()).decode()
        plt.close(fig2)
        return result_b64

    except Exception as e:
        logger.warning("[reduce_report] _squidpy_scatter_b64(%s) failed: %s", color, e)
        plt.close("all")
        return None



def _img_tag(b64: str, alt: str = "figure") -> str:
    return f'<img src="data:image/png;base64,{b64}" alt="{alt}">'


def _get_library_key(adata: ad.AnnData) -> Optional[str]:
    """Return the obs column that maps spots to their library/sample ID.

    Reading order (first match wins):
    1. ``uns["omicsage_spatial_ingest"]["library_key"]`` — set by spatial_ingest()
       using either the user-supplied value or auto-detection at load time.
    2. Auto-detection fallback — for h5ad files loaded outside OmicSage that
       lack the provenance key.

    Returns ``None`` for single-sample data (squidpy does not need library_key).
    """
    # 1. Read from ingest provenance (authoritative)
    ingest_prov = adata.uns.get("omicsage_spatial_ingest", {})
    if "library_key" in ingest_prov and ingest_prov["library_key"] is not None:
        return ingest_prov["library_key"]

    # 2. Auto-detection fallback
    library_ids = list(adata.uns.get("spatial", {}).keys())
    if len(library_ids) <= 1:
        return None
    id_set = set(library_ids)
    for candidate in ("library_id", "sample", "patient", "donor_id", "batch", "slide"):
        if candidate in adata.obs.columns:
            if id_set.issubset(set(adata.obs[candidate].astype(str).unique())):
                return candidate
    for col in adata.obs.columns:
        if adata.obs[col].dtype.name in ("object", "category"):
            if id_set.issubset(set(adata.obs[col].astype(str).unique())):
                return col
    return None


# ---------------------------------------------------------------------------
# Individual figure functions
# ---------------------------------------------------------------------------

def _fig_hvg_scatter(adata: ad.AnnData) -> Optional[str]:
    """Mean vs normalized dispersion, HVGs highlighted in orange."""
    required = {"means", "dispersions_norm", "highly_variable"}
    if not required.issubset(adata.var.columns):
        return None
    try:
        means = adata.var["means"].values
        disp  = adata.var["dispersions_norm"].values
        hvg   = adata.var["highly_variable"].values

        fig, ax = plt.subplots(figsize=(6, 4))
        ax.scatter(means[~hvg], disp[~hvg], s=3, alpha=0.3,
                   color="#95a5a6", label="non-HVG", rasterized=True)
        ax.scatter(means[hvg],  disp[hvg],  s=5, alpha=0.6,
                   color="#e67e22", label=f"HVG (n={hvg.sum():,})", rasterized=True)
        ax.set_xlabel("Mean expression")
        ax.set_ylabel("Normalized dispersion")
        ax.set_title("Highly Variable Genes", fontsize=10, fontweight="bold")
        ax.legend(fontsize=9, frameon=False)
        ax.spines[["top", "right"]].set_visible(False)
        fig.tight_layout()
        return _fig_to_b64(fig)
    except Exception as e:
        logger.warning("figure failed (%s): %s", __name__, e)
        return None


def _fig_pca_variance(adata: ad.AnnData, n_comps: int) -> Optional[str]:
    """Elbow plot: per-PC + cumulative variance explained."""
    try:
        vr   = np.array(adata.uns["pca"]["variance_ratio"])
        cumvr = np.cumsum(vr)
        pcs  = np.arange(1, len(vr) + 1)

        fig, ax1 = plt.subplots(figsize=(7, 4))
        ax2 = ax1.twinx()
        ax1.bar(pcs, vr * 100, color="#3498db", alpha=0.7)
        ax2.plot(pcs, cumvr * 100, color="#e74c3c", linewidth=2,
                 marker="o", markersize=3)
        ax2.axhline(90, color="#e74c3c", linestyle="--", linewidth=0.8, alpha=0.5)
        ax1.set_xlabel("Principal component")
        ax1.set_ylabel("Variance explained (%)", color="#3498db")
        ax2.set_ylabel("Cumulative variance (%)", color="#e74c3c")
        ax1.set_title("PCA — Variance Explained", fontsize=10, fontweight="bold")
        ax1.tick_params(axis="y", colors="#3498db")
        ax2.tick_params(axis="y", colors="#e74c3c")
        ax1.set_xlim(0.5, min(n_comps + 0.5, len(vr) + 0.5))
        ax1.spines[["top"]].set_visible(False)
        fig.tight_layout()
        return _fig_to_b64(fig)
    except Exception as e:
        logger.warning("figure failed (%s): %s", __name__, e)
        return None


def _fig_pca_scatter(adata: ad.AnnData) -> Optional[str]:
    """PCA scatter coloured by total_counts."""
    if "X_pca" not in adata.obsm:
        return None
    try:
        pca = adata.obsm["X_pca"]
        color_vals = (
            adata.obs["total_counts"].values
            if "total_counts" in adata.obs.columns
            else np.ones(adata.n_obs)
        )
        label = "total_counts" if "total_counts" in adata.obs.columns else ""

        fig, ax = plt.subplots(figsize=(5, 4))
        sc_plot = ax.scatter(pca[:, 0], pca[:, 1],
                             c=color_vals, cmap="viridis",
                             s=4, alpha=0.7, rasterized=True)
        plt.colorbar(sc_plot, ax=ax, label=label)
        ax.set_xlabel("PC1")
        ax.set_ylabel("PC2")
        ax.set_title("PCA — coloured by total counts", fontsize=10, fontweight="bold")
        ax.spines[["top", "right"]].set_visible(False)
        fig.tight_layout()
        return _fig_to_b64(fig)
    except Exception as e:
        logger.warning("figure failed (%s): %s", __name__, e)
        return None


def _fig_top_hvg_on_tissue(adata: ad.AnnData, img_key: Optional[str]) -> Optional[str]:
    """
    Spatial scatter of the top HVG overlaid on the H&E image (if available).
    Mirrors the tutorial plot: sq.pl.spatial_scatter(adata, color=top_gene, img_key=...).
    Falls back to no image if img_key is None or image is absent.
    """
    if not _SQUIDPY_AVAILABLE:
        return None
    if "spatial" not in adata.obsm or "spatial" not in adata.uns:
        return None
    if "highly_variable" not in adata.var.columns:
        return None

    # Pick the top HVG by normalized dispersion (most spatially interesting)
    hvg_mask = adata.var["highly_variable"]
    if not hvg_mask.any():
        return None
    if "dispersions_norm" in adata.var.columns:
        top_gene = (
            adata.var.loc[hvg_mask, "dispersions_norm"].idxmax()
        )
    else:
        top_gene = adata.var_names[hvg_mask][0]

    resolved_img_key = _resolve_img_key(adata, img_key)
    library_key = _get_library_key(adata)
    try:
        return _squidpy_scatter_b64(
            adata, color=top_gene,
            img_key=resolved_img_key, library_key=library_key,
            title=f"Top HVG: {top_gene}", figsize=_squidpy_panel_figsize(adata, per_panel=(7, 7)),
        )
    except Exception as e:
        logger.warning("figure failed (%s): %s", __name__, e)
        return None


def _fig_spatial_neighbours(adata: ad.AnnData) -> Optional[str]:
    """Histogram of number of spatial neighbours per spot (~6 for Visium grid)."""
    if "spatial_connectivities" not in adata.obsp:
        return None
    try:
        conn = adata.obsp["spatial_connectivities"]
        n_nb = np.array(conn.sum(axis=1)).ravel().astype(int)

        fig, ax = plt.subplots(figsize=(5, 3))
        unique, counts = np.unique(n_nb, return_counts=True)
        ax.bar(unique, counts, color="#2ecc71", edgecolor="white")
        ax.axvline(6, color="#e74c3c", linestyle="--", linewidth=1.2,
                   label="expected 6 (Visium grid)")
        ax.set_xlabel("Neighbours per spot")
        ax.set_ylabel("Number of spots")
        ax.set_title("Spatial neighbours distribution", fontsize=10, fontweight="bold")
        ax.legend(fontsize=8, frameon=False)
        ax.set_xticks(sorted(unique))
        ax.spines[["top", "right"]].set_visible(False)
        fig.tight_layout()
        return _fig_to_b64(fig)
    except Exception as e:
        logger.warning("figure failed (%s): %s", __name__, e)
        return None


# ---------------------------------------------------------------------------
# Utility
# ---------------------------------------------------------------------------

def _resolve_img_key(adata: ad.AnnData, img_key: Optional[str]) -> Optional[str]:
    """
    Return img_key if the image is actually present in adata.uns["spatial"],
    otherwise return None so figures degrade gracefully.
    """
    if img_key is None:
        return None
    spatial_uns = adata.uns.get("spatial", {})
    for _sample, sample_data in spatial_uns.items():
        images = sample_data.get("images", {})
        if img_key in images:
            return img_key
        # common aliases
        for alias in ("hires", "lowres"):
            if alias in images:
                return alias
    return None


# ---------------------------------------------------------------------------
# Sections
# ---------------------------------------------------------------------------

def _section_summary(adata: ad.AnnData, reduce_info: dict,
                     dataset_id: str, timestamp: str) -> str:
    params  = reduce_info.get("params", {})
    outputs = reduce_info.get("outputs", {})

    n_hvgs    = outputs.get("n_hvgs", "?")
    n_comps   = outputs.get("n_comps_computed", "?")
    n_edges   = outputs.get("spatial_graph_n_edges", "?")
    mean_nb   = outputs.get("spatial_graph_mean_neighbors", "?")
    cum_var   = outputs.get("pca_cumulative_variance_top10", None)
    cum_var_s = f"{cum_var * 100:.1f}%" if cum_var is not None else "?"
    skipped_norm = params.get("skipped_normalization", False)

    stat_cards = "".join(
        f'<div class="stat-card"><div class="stat-value">{v}</div>'
        f'<div class="stat-label">{k}</div></div>'
        for k, v in [
            ("Spots",              f"{adata.n_obs:,}"),
            ("Genes (total)",      f"{adata.n_vars:,}"),
            ("HVGs selected",      f"{n_hvgs:,}" if isinstance(n_hvgs, int) else n_hvgs),
            ("PCA components",     str(n_comps)),
            ("Variance (top 10 PCs)", cum_var_s),
            ("Spatial graph edges", f"{n_edges:,}" if isinstance(n_edges, int) else n_edges),
            ("Mean neighbours/spot", str(mean_nb)),
        ]
    )

    param_rows = "".join(
        f"<tr><td><code>{k}</code></td><td>{v}</td></tr>"
        for k, v in [
            ("normalize_total",  params.get("normalize_total", "?")),
            ("target_sum",       params.get("target_sum", "?")),
            ("log1p",            params.get("log1p", "?")),
            ("n_top_genes (HVG)", params.get("n_top_genes", "?")),
            ("hvg_flavor",       params.get("flavor", "?")),
            ("n_comps (PCA)",    params.get("n_comps", "?")),
            ("n_neighbors",      params.get("n_neighbors", "?")),
            ("coord_type",       params.get("coord_type") or "None (auto)"),
        ]
    )

    norm_note = (
        '<p class="note">⚠ Normalization skipped — benchmark dataset detected '
        "(pre-processed input).</p>"
        if skipped_norm else ""
    )

    return f"""
    <section>
      <h2>Run Summary</h2>
      <p class="timestamp">Dataset: <strong>{dataset_id}</strong> &middot; {timestamp}</p>
      {norm_note}
      <div class="stat-grid">{stat_cards}</div>
      <h3>Parameters</h3>
      <table>
        <thead><tr><th>Parameter</th><th>Value</th></tr></thead>
        <tbody>{param_rows}</tbody>
      </table>
    </section>
    """


def _section_hvg(adata: ad.AnnData) -> str:
    b64 = _fig_hvg_scatter(adata)
    if not b64:
        return ""
    return f"""
    <section>
      <h2>Highly Variable Gene Selection</h2>
      <p>Genes are ranked by normalized dispersion. HVGs (orange) are used for PCA and downstream clustering.</p>
      <div class="fig-grid">
        <div class="fig-wrap">
          <h3>Mean expression vs normalized dispersion</h3>
          {_img_tag(b64, "HVG scatter")}
        </div>
      </div>
    </section>
    """


def _section_pca(adata: ad.AnnData, n_comps: int) -> str:
    b64_var     = _fig_pca_variance(adata, n_comps)
    b64_scatter = _fig_pca_scatter(adata)
    if not b64_var and not b64_scatter:
        return ""
    figs = ""
    if b64_var:
        figs += (
            '<div class="fig-wrap">'
            "<h3>Variance explained (elbow plot)</h3>"
            + _img_tag(b64_var, "PCA variance")
            + "</div>"
        )
    if b64_scatter:
        figs += (
            '<div class="fig-wrap">'
            "<h3>PCA — spots coloured by total counts</h3>"
            + _img_tag(b64_scatter, "PCA scatter")
            + "</div>"
        )
    return f"""
    <section>
      <h2>PCA</h2>
      <p>PCA run on HVGs. The elbow plot shows variance explained per component; the red dashed line marks 90% cumulative variance.</p>
      <div class="fig-grid">{figs}</div>
    </section>
    """


def _section_spatial_structure(adata: ad.AnnData, img_key: Optional[str]) -> str:
    b64_hvg = _fig_top_hvg_on_tissue(adata, img_key)
    b64_nb  = _fig_spatial_neighbours(adata)
    if not b64_hvg and not b64_nb:
        return ""
    figs = ""
    if b64_hvg:
        resolved = _resolve_img_key(adata, img_key)
        subtitle = (
            "Top HVG expression overlaid on H&amp;E image"
            if resolved
            else "Top HVG expression on tissue array (no H&amp;E image available)"
        )
        figs += (
            '<div class="fig-wrap">'
            f"<h3>{subtitle}</h3>"
            + _img_tag(b64_hvg, "top HVG on tissue")
            + "</div>"
        )
    if b64_nb:
        figs += (
            '<div class="fig-wrap">'
            "<h3>Spatial neighbours per spot</h3>"
            + _img_tag(b64_nb, "neighbours histogram")
            + "</div>"
        )
    return f"""
    <section>
      <h2>Spatial Structure</h2>
      <p>Left: expression of the most variable gene overlaid on the tissue array.
         Right: distribution of spatial neighbours per spot — Visium grids produce 6 neighbours for interior spots.</p>
      <div class="fig-grid">{figs}</div>
    </section>
    """


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def generate_spatial_reduce_report(
    adata: ad.AnnData,
    output_path: str,
    dataset_id: str = "spatial",
    img_key: Optional[str] = "hires",
) -> str:
    """Generate a self-contained HTML reduction report for Visium data.

    Parameters
    ----------
    adata
        AnnData returned by :func:`spatial_reduce`.
    output_path
        Path to write the ``.html`` file.
    dataset_id
        Dataset label shown in the report header.
    img_key
        H&E image key stored in ``adata.uns["spatial"][sample]["images"]``.
        Common values: ``"hires"`` (default), ``"lowres"``.
        If the image is absent the figure degrades gracefully to spots-only.

    Returns
    -------
    str
        Absolute path to the written HTML file.
    """
    if "omicsage_spatial_reduce" not in adata.uns:
        raise ValueError(
            "adata.uns['omicsage_spatial_reduce'] not found. "
            "Run spatial_reduce() before generating the report."
        )

    timestamp   = datetime.now().strftime("%Y-%m-%d %H:%M")
    reduce_info = adata.uns["omicsage_spatial_reduce"]
    n_comps     = reduce_info.get("outputs", {}).get("n_comps_computed", 50)

    sections = [
        _section_summary(adata, reduce_info, dataset_id, timestamp),
        _section_hvg(adata),
        _section_pca(adata, n_comps),
        _section_spatial_structure(adata, img_key),
    ]

    html = _render_page(
        title=f"OmicSage -- Spatial Reduce -- {dataset_id}",
        header_subtitle=f"Dataset: {dataset_id}",
        sections=sections,
        timestamp=timestamp,
    )

    output_path = str(output_path)
    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    Path(output_path).write_text(html, encoding="utf-8")
    size_kb = Path(output_path).stat().st_size / 1024
    logger.info("Spatial reduce report -> %s (%.1f KB)", output_path, size_kb)
    return str(Path(output_path).resolve())
