"""
spatial_cluster_report.py — OmicSage Phase 7, Session 5 (style update)
HTML report for spatial clustering and spatially variable gene results.

Style: matches spatial_qc_report.py exactly (_PAGE_CSS / _render_page pattern).

Sections:
  1. Run Summary       — stat cards: n_clusters, n_spots, resolution, n_SVGs
  2. Clustering        — spatial scatter on tissue (with H&E) + cluster size bar chart
  3. Spatially variable genes — Moran's I bar chart + top 3 SVGs on tissue + SVG table
"""

from __future__ import annotations

import base64
import logging
from datetime import datetime
from io import BytesIO
from pathlib import Path
from typing import Optional

import anndata as ad
import matplotlib
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

matplotlib.use("Agg")
logger = logging.getLogger(__name__)

try:
    import squidpy as sq
    _SQUIDPY_AVAILABLE = True
except ImportError:
    _SQUIDPY_AVAILABLE = False


# ---------------------------------------------------------------------------
# Shared CSS + page renderer  (identical to spatial_qc_report.py)
# ---------------------------------------------------------------------------

_PAGE_CSS = """
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
           font-size: 14px; line-height: 1.6; color: #1a1a2e; background: #f7f8fc; }
    header { background: linear-gradient(135deg, #1a1a2e 0%, #16213e 60%, #0f3460 100%);
             color: white; padding: 32px 40px 24px; }
    header h1 { font-size: 1.8rem; font-weight: 700; letter-spacing: -0.5px; }
    header p  { font-size: 0.85rem; opacity: 0.7; margin-top: 4px; }
    main { max-width: 1100px; margin: 0 auto; padding: 32px 24px; }
    section { background: white; border-radius: 10px;
              box-shadow: 0 1px 4px rgba(0,0,0,0.07);
              padding: 28px 32px; margin-bottom: 24px; }
    section h2 { font-size: 1.15rem; font-weight: 700; color: #0f3460;
                 border-bottom: 2px solid #e8eaf6; padding-bottom: 10px; margin-bottom: 18px; }
    section h3 { font-size: 1rem; font-weight: 600; color: #16213e; margin: 18px 0 10px; }
    section p  { color: #444; margin-bottom: 12px; font-size: 0.9rem; }
    .timestamp { font-size: 0.8rem; color: #888; margin-bottom: 6px; }
    .note { font-size: 0.82rem; color: #7a5c00; background: #fffbe6;
            border-left: 3px solid #f0c040; padding: 8px 12px;
            border-radius: 4px; margin-bottom: 14px; }
    code { font-family: "SFMono-Regular", Consolas, monospace;
           background: #f0f2ff; padding: 1px 5px; border-radius: 3px; font-size: 0.85em; }
    .stat-grid { display: flex; flex-wrap: wrap; gap: 14px; margin-bottom: 24px; }
    .stat-card { background: #f0f2ff; border-radius: 8px; padding: 14px 20px;
                 min-width: 130px; text-align: center; flex: 1 1 130px; }
    .stat-value { font-size: 1.4rem; font-weight: 700; color: #0f3460; }
    .stat-label { font-size: 0.75rem; color: #666; margin-top: 2px; }
    table { width: 100%; border-collapse: collapse; font-size: 0.88rem; margin-top: 8px; }
    th { background: #f0f2ff; color: #0f3460; font-weight: 600;
         padding: 9px 12px; text-align: left; border-bottom: 2px solid #d0d4f0; }
    td { padding: 8px 12px; border-bottom: 1px solid #eee; vertical-align: middle; }
    tr:last-child td { border-bottom: none; }
    tr:hover td { background: #f8f9ff; }
    .fig-grid { display: flex; flex-wrap: wrap; gap: 18px; margin-top: 12px; }
    .fig-wrap { flex: 1 1 420px; max-width: 100%; }
    .fig-wrap h3 { font-size: 0.9rem; margin-bottom: 6px; color: #16213e; }
    .fig-wrap img { width: 100%; border-radius: 6px; border: 1px solid #e8eaf6; cursor: zoom-in; display: block; }
    footer { text-align: center; font-size: 0.78rem; color: #aaa; padding: 24px 0 32px; }
    footer a { color: #0f3460; text-decoration: none; }
"""


def _render_page(title: str, header_subtitle: str, sections: list[str], timestamp: str) -> str:
    body = "\n".join(sections)
    return (
        "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n"
        "  <meta charset=\"UTF-8\">\n"
        "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
        f"  <title>{title}</title>\n"
        f"  <style>{_PAGE_CSS}</style>\n"
        "</head>\n<body>\n"
        "  <header>\n"
        "    <h1>OmicSage &#8212; Spatial Cluster Report</h1>\n"
        f"    <p>{header_subtitle} &middot; Generated {timestamp}</p>\n"
        "  </header>\n"
        "  <main>\n"
        f"    {body}\n"
        "  </main>\n"
        "  <footer>\n"
        "    Generated by <a href=\"https://github.com/fshokor/OmicSage\">OmicSage</a>\n"
        "    &middot; MIT License\n"
        "  </footer>\n"
        "</body>\n</html>"
    )


# ---------------------------------------------------------------------------
# Figure helpers
# ---------------------------------------------------------------------------


def _squidpy_panel_figsize(adata, per_panel=(6, 6), max_total_w=18):
    """Return per-panel figsize; always square, regardless of sample count.

    Multi-sample layouts are handled by _squidpy_scatter_b64 which renders
    each sample separately and stitches them into a grid — so this function
    just returns the single-panel size unchanged.
    """
    return per_panel


def _fig_to_b64(fig: plt.Figure) -> str:
    buf = BytesIO()
    fig.savefig(buf, format="png", dpi=100, bbox_inches="tight")
    buf.seek(0)
    b64 = base64.b64encode(buf.read()).decode()
    plt.close(fig)
    return b64


def _squidpy_scatter_b64(
    adata,
    color,
    img_key=None,
    library_key=None,
    title=None,
    figsize=(6, 6),
):
    """Render sq.pl.spatial_scatter and return a base64 PNG.

    Multi-sample strategy
    ---------------------
    When ``library_key`` is set and there are ≥2 samples, squidpy lays all
    samples side-by-side in one figure.  With 4 samples this produces an
    image ~5700×640 px (aspect ratio ~9:1) which renders as a barely-visible
    strip when scaled to fit a normal browser column.

    Instead we render each sample individually (one clean square figure per
    sample) and stitch them into a 2-column grid.  This gives each sample
    enough vertical space to be readable at any zoom level.  Single-sample
    data takes the fast path (one squidpy call, no stitching).
    """
    import numpy as _np
    import io as _io
    import base64 as _b64_mod

    if not _SQUIDPY_AVAILABLE:
        return None

    try:
        samples = []
        if library_key and library_key in adata.obs.columns:
            samples = sorted(adata.obs[library_key].astype(str).unique().tolist())

        # ── Single-sample fast path ──────────────────────────────────────────
        if len(samples) <= 1:
            plt.close("all")
            kwargs = dict(color=color, frameon=False, figsize=figsize)
            if img_key:
                kwargs["img_res_key"] = img_key
            result = sq.pl.spatial_scatter(adata, **kwargs)
            if result is None:
                fig = plt.gcf()
            elif hasattr(result, "get_figure"):
                fig = result.get_figure()
            elif hasattr(result, "__len__") and len(result) > 0:
                ax0 = result[0]
                fig = ax0.get_figure() if hasattr(ax0, "get_figure") else plt.gcf()
            else:
                fig = plt.gcf()
            if not fig.axes:
                all_figs = [plt.figure(n) for n in plt.get_fignums()]
                if all_figs:
                    fig = all_figs[-1]
            if title:
                fig.suptitle(title, fontsize=10, fontweight="bold")
            try:
                fig.tight_layout()
            except Exception:
                pass
            return _fig_to_b64(fig)

        # ── Multi-sample: render each sample separately, stitch 2-column grid ─
        per_b64s: list[tuple[str, str]] = []   # (sample_label, b64)
        for sample_id in samples:
            try:
                mask = adata.obs[library_key].astype(str) == sample_id
                ad_sub = adata[mask].copy()
                # uns["spatial"] is NOT filtered by obs subsetting — prune to
                # the current sample so squidpy doesn't demand a library_key.
                if "spatial" in ad_sub.uns and sample_id in ad_sub.uns["spatial"]:
                    ad_sub.uns["spatial"] = {sample_id: ad_sub.uns["spatial"][sample_id]}
                plt.close("all")
                kwargs = dict(color=color, frameon=False, figsize=figsize)
                if img_key:
                    kwargs["img_res_key"] = img_key
                result = sq.pl.spatial_scatter(ad_sub, **kwargs)
                if result is None:
                    fig = plt.gcf()
                elif hasattr(result, "get_figure"):
                    fig = result.get_figure()
                elif hasattr(result, "__len__") and len(result) > 0:
                    ax0 = result[0]
                    fig = ax0.get_figure() if hasattr(ax0, "get_figure") else plt.gcf()
                else:
                    fig = plt.gcf()
                if not fig.axes:
                    all_figs = [plt.figure(n) for n in plt.get_fignums()]
                    if all_figs:
                        fig = all_figs[-1]
                try:
                    fig.tight_layout()
                except Exception:
                    pass
                # Export panel to in-memory PNG
                buf = _io.BytesIO()
                fig.savefig(buf, format="png", dpi=100, bbox_inches="tight")
                buf.seek(0)
                per_b64s.append((sample_id, _b64_mod.b64encode(buf.read()).decode()))
                plt.close(fig)
            except Exception as e:
                logger.warning("[cluster_report] scatter failed for sample %s: %s", sample_id, e)
                plt.close("all")

        if not per_b64s:
            return None

        # ── Stitch panels into a 2-column grid ───────────────────────────────
        imgs = []
        for _, b in per_b64s:
            arr = plt.imread(_io.BytesIO(_b64_mod.b64decode(b)))
            imgs.append(arr)

        ncols = 2
        nrows = (len(imgs) + ncols - 1) // ncols
        max_h = max(a.shape[0] for a in imgs)
        max_w = max(a.shape[1] for a in imgs)
        n_ch  = imgs[0].shape[2] if imgs[0].ndim == 3 else 1

        def _pad(a):
            ph = max_h - a.shape[0]
            pw = max_w - a.shape[1]
            return _np.pad(a, ((0, ph), (0, pw), (0, 0)),
                           mode="constant", constant_values=1.0)

        padded = [_pad(a) for a in imgs]
        # Fill incomplete last row with white
        while len(padded) < nrows * ncols:
            padded.append(_np.ones((max_h, max_w, n_ch), dtype=padded[0].dtype))

        rows = [_np.hstack(padded[r * ncols:(r + 1) * ncols]) for r in range(nrows)]
        grid = _np.vstack(rows)

        # Render the grid as a figure with an optional suptitle
        dpi = 100
        fig_w = grid.shape[1] / dpi
        fig_h = grid.shape[0] / dpi
        # Add a small margin at the top for the suptitle when needed
        title_pad = 0.35 if title else 0.0
        fig2, ax2 = plt.subplots(figsize=(fig_w, fig_h + title_pad), dpi=dpi)
        ax2.imshow(grid)
        ax2.axis("off")
        if title:
            fig2.suptitle(title, fontsize=10, fontweight="bold",
                          y=1.0 - (title_pad * 0.05 / (fig_h + title_pad)))
        # Annotate each panel with its sample label
        for idx, (sample_id, _) in enumerate(per_b64s):
            row_i = idx // ncols
            col_i = idx % ncols
            x_px = col_i * max_w + max_w * 0.02
            y_px = row_i * max_h + max_h * 0.04
            ax2.text(x_px, y_px, sample_id, fontsize=8, fontweight="bold",
                     color="white", va="top",
                     bbox=dict(facecolor="black", alpha=0.45, pad=2, linewidth=0))
        fig2.subplots_adjust(left=0, right=1, top=1, bottom=0)

        buf2 = _io.BytesIO()
        fig2.savefig(buf2, format="png", dpi=dpi, bbox_inches="tight")
        buf2.seek(0)
        result_b64 = _b64_mod.b64encode(buf2.read()).decode()
        plt.close(fig2)
        return result_b64

    except Exception as e:
        logger.warning("[cluster_report] _squidpy_scatter_b64(%s) failed: %s", color, e)
        plt.close("all")
        return None



def _img_tag(b64: str, alt: str = "figure") -> str:
    return f'<img src="data:image/png;base64,{b64}" alt="{alt}">'


def _resolve_img_key(adata: ad.AnnData, img_key: Optional[str]) -> Optional[str]:
    """Return img_key if the image is present, otherwise try hires/lowres, else None."""
    if img_key is None:
        return None
    spatial_uns = adata.uns.get("spatial", {})
    for _sample, sample_data in spatial_uns.items():
        images = sample_data.get("images", {})
        if img_key in images:
            return img_key
        for alias in ("hires", "lowres"):
            if alias in images:
                return alias
    return None


def _get_library_key(adata: ad.AnnData) -> Optional[str]:
    """Return the obs column that maps spots to their library/sample ID.

    Reading order (first match wins):
    1. ``uns["omicsage_spatial_ingest"]["library_key"]`` — set by spatial_ingest()
       using either the user-supplied value or auto-detection at load time.
    2. Auto-detection fallback — for h5ad files loaded outside OmicSage that
       lack the provenance key.

    Returns ``None`` for single-sample data (squidpy does not need library_key).
    """
    # 1. Read from ingest provenance (authoritative)
    ingest_prov = adata.uns.get("omicsage_spatial_ingest", {})
    if "library_key" in ingest_prov and ingest_prov["library_key"] is not None:
        return ingest_prov["library_key"]

    # 2. Auto-detection fallback
    library_ids = list(adata.uns.get("spatial", {}).keys())
    if len(library_ids) <= 1:
        return None
    id_set = set(library_ids)
    for candidate in ("library_id", "sample", "patient", "donor_id", "batch", "slide"):
        if candidate in adata.obs.columns:
            if id_set.issubset(set(adata.obs[candidate].astype(str).unique())):
                return candidate
    for col in adata.obs.columns:
        if adata.obs[col].dtype.name in ("object", "category"):
            if id_set.issubset(set(adata.obs[col].astype(str).unique())):
                return col
    return None


# ---------------------------------------------------------------------------
# Individual figure functions
# ---------------------------------------------------------------------------

def _fig_clusters_on_tissue(
    adata: ad.AnnData,
    cluster_key: str,
    img_key: Optional[str],
) -> Optional[str]:
    """
    Spatial scatter of Leiden clusters overlaid on the H&E tissue image.
    Mirrors the tutorial: sq.pl.spatial_scatter(adata, color=cluster_key, img_key=...).
    Degrades gracefully to spots-only when image is absent.
    """
    if not _SQUIDPY_AVAILABLE:
        return None
    if "spatial" not in adata.obsm or "spatial" not in adata.uns:
        return None
    if cluster_key not in adata.obs.columns:
        return None

    resolved = _resolve_img_key(adata, img_key)
    library_key = _get_library_key(adata)
    suffix = " (on H&E)" if resolved else ""
    try:
        return _squidpy_scatter_b64(
            adata, color=cluster_key,
            img_key=resolved, library_key=library_key,
            title=f"Leiden clusters{suffix}", figsize=_squidpy_panel_figsize(adata, per_panel=(7, 7)),
        )
    except Exception as e:
        logger.warning("figure failed (%s): %s", __name__, e)
        return None


def _fig_cluster_sizes(cluster_info: dict) -> Optional[str]:
    """Horizontal bar chart of spots per Leiden cluster."""
    sizes = cluster_info.get("outputs", {}).get("cluster_sizes", {})
    if not sizes:
        return None
    try:
        try:
            labels = sorted(sizes.keys(), key=lambda x: int(x))
        except ValueError:
            labels = sorted(sizes.keys())
        values = [sizes[k] for k in labels]

        fig, ax = plt.subplots(figsize=(5, max(3, len(labels) * 0.35)))
        colors = plt.cm.tab20(np.linspace(0, 1, len(labels)))
        ax.barh(labels, values, color=colors, edgecolor="white")
        ax.set_xlabel("Number of spots")
        ax.set_ylabel("Cluster")
        ax.set_title("Spots per cluster", fontsize=10, fontweight="bold")
        ax.invert_yaxis()
        for i, val in enumerate(values):
            ax.text(val + max(values) * 0.01, i, str(val), va="center", fontsize=8)
        ax.spines[["top", "right"]].set_visible(False)
        fig.tight_layout()
        return _fig_to_b64(fig)
    except Exception as e:
        logger.warning("figure failed (%s): %s", __name__, e)
        return None


def _fig_svg_bar(adata: ad.AnnData) -> Optional[str]:
    """Horizontal bar chart of Moran's I scores for the top 20 SVGs."""
    if "moranI" not in adata.uns:
        return None
    try:
        moran_df: pd.DataFrame = adata.uns["moranI"]
        top = moran_df.head(20).copy()
        genes  = top.index.tolist()
        scores = top["I"].values
        sig    = top["pval_norm_fdr_bh"].values < 0.05

        colors = ["#e74c3c" if s else "#95a5a6" for s in sig]
        fig, ax = plt.subplots(figsize=(7, max(3, len(genes) * 0.35)))
        ax.barh(genes, scores, color=colors, edgecolor="white")
        ax.set_xlabel("Moran's I")
        ax.set_title("Top spatially variable genes (red = FDR < 0.05)",
                     fontsize=10, fontweight="bold")
        ax.invert_yaxis()
        ax.set_xlim(0, max(scores) * 1.15)
        ax.spines[["top", "right"]].set_visible(False)
        fig.tight_layout()
        return _fig_to_b64(fig)
    except Exception as e:
        logger.warning("figure failed (%s): %s", __name__, e)
        return None


def _fig_top_svgs_on_tissue(
    adata: ad.AnnData,
    img_key: Optional[str],
    n_top: int = 4,
) -> Optional[str]:
    """
    Spatial scatter of the top N SVGs overlaid on the H&E tissue image.
    Tutorial standard: one panel per gene, img_key for background.
    Using n_top=4 to show a 2×2 grid which makes better use of space.
    """
    if not _SQUIDPY_AVAILABLE:
        return None
    if "moranI" not in adata.uns:
        return None
    if "spatial" not in adata.obsm or "spatial" not in adata.uns:
        return None

    moran_df: pd.DataFrame = adata.uns["moranI"]
    top_genes = [g for g in moran_df.head(n_top).index if g in adata.var_names]
    if not top_genes:
        return None

    resolved = _resolve_img_key(adata, img_key)
    library_key = _get_library_key(adata)
    # Render each gene separately (squidpy owns the figure per call),
    # then stitch all panels into one image.
    try:
        import base64 as _b64, io as _io
        import numpy as _np

        b64s = []
        for gene in top_genes:
            score = moran_df.loc[gene, "I"] if gene in moran_df.index else None
            title = gene if score is None else f"{gene}  (I = {score:.3f})"
            b = _squidpy_scatter_b64(
                adata, color=gene,
                img_key=resolved, library_key=library_key,
                title=title, figsize=_squidpy_panel_figsize(adata, per_panel=(7, 7)),
            )
            if b:
                b64s.append(b)

        if not b64s:
            return None

        # Load each panel as a numpy array and stitch into a 2-column grid
        imgs = [plt.imread(_io.BytesIO(_b64.b64decode(b))) for b in b64s]
        ncols = min(len(imgs), 2)
        nrows = (len(imgs) + ncols - 1) // ncols

        # Pad all images to the same size
        max_h = max(a.shape[0] for a in imgs)
        max_w = max(a.shape[1] for a in imgs)
        ch    = imgs[0].shape[2] if imgs[0].ndim == 3 else 1

        def pad_img(a):
            ph = max_h - a.shape[0]
            pw = max_w - a.shape[1]
            return _np.pad(a, ((0, ph), (0, pw), (0, 0)),
                           mode="constant", constant_values=1)

        padded = [pad_img(a) for a in imgs]
        # Fill grid with white panels if odd number of images
        while len(padded) < nrows * ncols:
            padded.append(_np.ones((max_h, max_w, ch), dtype=padded[0].dtype))

        rows = [_np.hstack(padded[r * ncols:(r + 1) * ncols]) for r in range(nrows)]
        grid = _np.vstack(rows)

        TARGET_W = 1800
        raw_w = grid.shape[1]
        raw_h = grid.shape[0]
        scale = min(1.0, TARGET_W / raw_w)
        fig2, ax2 = plt.subplots(figsize=(raw_w * scale / 100, raw_h * scale / 100), dpi=100)
        ax2.imshow(grid)
        ax2.axis("off")
        suffix = " on H&E" if resolved else ""
        fig2.suptitle(f"Top {len(top_genes)} spatially variable genes{suffix}",
                      fontsize=10, fontweight="bold", y=1.01)
        fig2.tight_layout(pad=0)
        return _fig_to_b64(fig2)
    except Exception as e:
        logger.warning("figure failed (%s): %s", __name__, e)
        return None


# ---------------------------------------------------------------------------
# Sections
# ---------------------------------------------------------------------------

def _section_summary(
    adata: ad.AnnData,
    cluster_info: dict,
    dataset_id: str,
    timestamp: str,
) -> str:
    params  = cluster_info.get("params", {})
    outputs = cluster_info.get("outputs", {})

    n_clusters   = outputs.get("n_clusters", "?")
    n_svg_sig    = outputs.get("n_significant_fdr05", None)
    n_svg_tested = outputs.get("n_genes_tested", None)
    top5_svg     = outputs.get("top5_svg", [])
    resolution   = params.get("resolution", "?")
    cluster_key  = params.get("cluster_key", "spatial_cluster")
    run_svg      = params.get("run_svg", False)
    has_annot    = params.get("annotation_map_provided", False)

    stat_cards = "".join(
        f'<div class="stat-card"><div class="stat-value">{v}</div>'
        f'<div class="stat-label">{k}</div></div>'
        for k, v in [
            ("Spots",          f"{adata.n_obs:,}"),
            ("Leiden clusters", str(n_clusters)),
            ("Resolution",     str(resolution)),
        ]
        + (
            [("SVGs (FDR<0.05)", str(n_svg_sig)),
             ("Genes tested",   f"{n_svg_tested:,}" if isinstance(n_svg_tested, int) else str(n_svg_tested))]
            if n_svg_sig is not None else []
        )
    )

    top5_html = " ".join(
        f'<code>{g}</code>' for g in top5_svg
    ) if top5_svg else "<em>none</em>"

    annot_note = (
        '<p class="note">Cluster labels annotated using <code>annotation_map</code>.</p>'
        if has_annot else ""
    )

    param_rows = "".join(
        f"<tr><td><code>{k}</code></td><td>{v}</td></tr>"
        for k, v in [
            ("cluster_key",     cluster_key),
            ("resolution",      resolution),
            ("n_neighbors (KNN)", params.get("n_neighbors", "?")),
            ("n_pcs",           params.get("n_pcs_actual", "?")),
            ("run_svg",         str(run_svg)),
            ("annotation_map",  "yes" if has_annot else "no"),
        ]
    )

    return f"""
    <section>
      <h2>Run Summary</h2>
      <p class="timestamp">Dataset: <strong>{dataset_id}</strong> &middot; {timestamp}</p>
      {annot_note}
      <div class="stat-grid">{stat_cards}</div>
      {"<h3>Top SVGs</h3><p>" + top5_html + "</p>" if top5_svg else ""}
      <h3>Parameters</h3>
      <table>
        <thead><tr><th>Parameter</th><th>Value</th></tr></thead>
        <tbody>{param_rows}</tbody>
      </table>
    </section>
    """


def _section_clustering(
    adata: ad.AnnData,
    cluster_info: dict,
    img_key: Optional[str],
) -> str:
    cluster_key = cluster_info.get("params", {}).get("cluster_key", "spatial_cluster")
    b64_tissue  = _fig_clusters_on_tissue(adata, cluster_key, img_key)
    b64_sizes   = _fig_cluster_sizes(cluster_info)

    if not b64_tissue and not b64_sizes:
        return ""

    resolved = _resolve_img_key(adata, img_key)
    tissue_title = (
        "Leiden clusters overlaid on H&amp;E image"
        if resolved
        else "Leiden clusters on tissue array"
    )

    figs = ""
    if b64_tissue:
        figs += (
            '<div class="fig-wrap">'
            f"<h3>{tissue_title}</h3>"
            + _img_tag(b64_tissue, "clusters on tissue")
            + "</div>"
        )
    if b64_sizes:
        figs += (
            '<div class="fig-wrap">'
            "<h3>Spots per cluster</h3>"
            + _img_tag(b64_sizes, "cluster size bar chart")
            + "</div>"
        )
    return f"""
    <section>
      <h2>Leiden Clustering</h2>
      <p>Spots are clustered using the Leiden algorithm on the KNN graph built from PCA embeddings.
         Cluster colours are consistent between the spatial and size panels.</p>
      <div class="fig-grid">{figs}</div>
    </section>
    """


def _section_svg(adata: ad.AnnData, img_key: Optional[str]) -> str:
    if "moranI" not in adata.uns:
        return ""

    b64_bar    = _fig_svg_bar(adata)
    b64_tissue = _fig_top_svgs_on_tissue(adata, img_key, n_top=4)

    # Build SVG table
    try:
        moran_df: pd.DataFrame = adata.uns["moranI"]
        top20 = moran_df.head(20).reset_index()
        rows = ""
        for _, row in top20.iterrows():
            sig_badge = (
                '<span style="color:#e74c3c;font-weight:700;">★</span>'
                if row.get("pval_norm_fdr_bh", 1.0) < 0.05
                else ""
            )
            rows += (
                f"<tr><td>{row.iloc[0]}</td>"
                f"<td>{row['I']:.4f}</td>"
                f"<td>{row.get('pval_norm', float('nan')):.2e}</td>"
                f"<td>{row.get('pval_norm_fdr_bh', float('nan')):.2e} {sig_badge}</td>"
                f"</tr>"
            )
        n_total = len(moran_df)
        svg_table = f"""
        <h3>Top 20 SVGs</h3>
        <table>
          <thead>
            <tr><th>Gene</th><th>Moran's I</th><th>p-value</th><th>FDR-adjusted p</th></tr>
          </thead>
          <tbody>{rows}</tbody>
        </table>
        <p class="note">&#9733; = FDR &lt; 0.05 &nbsp;&middot;&nbsp; Showing top 20 of {n_total:,} tested genes</p>
        """
    except Exception as e:
        logger.warning("SVG table failed: %s", e)
        svg_table = "<p><em>SVG table could not be rendered.</em></p>"

    figs = ""
    if b64_bar:
        figs += (
            '<div class="fig-wrap">'
            "<h3>Moran's I scores — top 20 SVGs</h3>"
            + _img_tag(b64_bar, "Moran's I bar chart")
            + "</div>"
        )
    if b64_tissue:
        resolved = _resolve_img_key(adata, img_key)
        subtitle = (
            "Top SVGs overlaid on H&amp;E image"
            if resolved
            else "Top SVGs on tissue array"
        )
        figs += (
            '<div class="fig-wrap">'
            f"<h3>{subtitle}</h3>"
            + _img_tag(b64_tissue, "top SVGs on tissue")
            + "</div>"
        )

    return f"""
    <section>
      <h2>Spatially Variable Genes (Moran's I)</h2>
      <p>Moran's I measures spatial autocorrelation: genes with high scores are expressed
         in spatially coherent patterns rather than randomly across spots.
         Red bars indicate significance at FDR &lt; 0.05.</p>
      <div class="fig-grid">{figs}</div>
      {svg_table}
    </section>
    """


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def generate_spatial_cluster_report(
    adata: ad.AnnData,
    output_path: str,
    dataset_id: str = "spatial",
    img_key: Optional[str] = "hires",
) -> str:
    """Generate a self-contained HTML clustering report for Visium data.

    Parameters
    ----------
    adata
        AnnData returned by :func:`spatial_cluster`.
    output_path
        Path to write the ``.html`` file.
    dataset_id
        Dataset label shown in the report header.
    img_key
        H&E image key stored in ``adata.uns["spatial"][sample]["images"]``.
        Common values: ``"hires"`` (default), ``"lowres"``.
        If the image is absent the figures degrade gracefully to spots-only.

    Returns
    -------
    str
        Absolute path to the written HTML file.
    """
    if "omicsage_spatial_cluster" not in adata.uns:
        raise ValueError(
            "adata.uns['omicsage_spatial_cluster'] not found. "
            "Run spatial_cluster() before generating the report."
        )

    timestamp    = datetime.now().strftime("%Y-%m-%d %H:%M")
    cluster_info = adata.uns["omicsage_spatial_cluster"]

    sections = [
        _section_summary(adata, cluster_info, dataset_id, timestamp),
        _section_clustering(adata, cluster_info, img_key),
        _section_svg(adata, img_key),
    ]

    html = _render_page(
        title=f"OmicSage -- Spatial Cluster -- {dataset_id}",
        header_subtitle=f"Dataset: {dataset_id}",
        sections=sections,
        timestamp=timestamp,
    )

    output_path = str(output_path)
    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    Path(output_path).write_text(html, encoding="utf-8")
    size_kb = Path(output_path).stat().st_size / 1024
    logger.info("Spatial cluster report -> %s (%.1f KB)", output_path, size_kb)
    return str(Path(output_path).resolve())
